version: '2.1'
services:

  dataease-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: 1.11.1
    container_name: dataease-backend
    restart: always
    volumes:
      - /Users/nico/workspace/soft/dataease/backend/target:/opt/apps
      - /opt/dataease/conf:/opt/dataease/conf
    ports:
      - 8081:8081
    networks:
      - dataease_dataease-network
  
networks:
  dataease_dataease-network:
    external: true
